name: Demo
run-name: Demo instance
on: [push]
jobs:
  run-python:
    runs-on: ubuntu-latest
    steps:
      - name: import code
        uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: testing the code
        run: python test.py
      - run: echo "job complete"
