name: Demo
run-name: Demo instance
on: [push]
jobs:
  run-python:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Checkout
        uses: actions/checkout@v3.5.3
      - name: testing the code
        run: python test.py
      - run: echo "job complete"

      - uses: actions/upload-artifact@v3
        with:
          name: performance_logs
          path: logs.txt

      - uses: actions/checkout@v3

      - run: mkdir -p path/to/artifact

      - run: echo hello > path/to/artifact/world.txt

      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: path/to/artifact/world.txt

  test:
    needs: run-python
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3
      - run: python secrets.py


